### ISSUE TITLE
Reobfuscating with minecraft.class edited will crash when loading the game in the offical launcher?

### ISSUE THREAD

**Issue by LiEnby** [ModificationStation/1.7.3-LTS#36]
All i did was change` if (this.isMultiplayerWorld() && Keyboard.getEventKey() == this.gameSettings.keyBindChat.keyCode) {` to 
`if (Keyboard.getEventKey() == this.gameSettings.keyBindChat.keyCode) {`
so i could use the chat in singleplayer, but when i load the thing in the launcher the game crashes.
```

02:11:22.120
Preparing to launch minecraft client for b1.7.3-SilicaClient
02:11:23.075
Couldn't fetch SHA1 checksum for https://s3.amazonaws.com/Minecraft.Download/versions/b1.7.3-SilicaClient/b1.7.3-SilicaClient.jar
02:11:23.077
Have local file C:\Users\User\AppData\Roaming\.minecraft\versions\b1.7.3-SilicaClient\b1.7.3-SilicaClient.jar but don't know what size or hash it should be. Have to assume it's good.
02:11:23.078
Checking installations.
02:11:23.079
Minecraft client b1.7.3-SilicaClient is ready to start.
02:11:23.079
Starting!
02:11:23.886
Version does not support log configuration, will assume one plaintext entry per line
02:11:39.103
Dec 16, 2020 2:11:39 AM net.minecraft.launchwrapper.LogWrapper log
02:11:39.103
INFO: Using tweak class name net.minecraft.launchwrapper.VanillaTweaker
02:11:39.136
Dec 16, 2020 2:11:39 AM net.minecraft.launchwrapper.LogWrapper log
02:11:39.136
SEVERE: Unable to launch
02:11:39.137
java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
02:11:39.137
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:179)
02:11:39.137
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
02:11:39.137
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
02:11:39.137
at java.lang.Class.forName0(Native Method)
```

**Comment by moderatorman** [comment]
I'm kinda shocked nobody answered this. I believe you can fix it by simply deleting `MOJANG_C.SF` & `MOJANG_C.DSA` from META-INF.
