### ISSUE TITLE
Zip extraction failure when reobfuscating

### ISSUE THREAD

**Issue by moderatorman** [ModificationStation/1.7.3-LTS#40]
Beta 1.7.3, OpenJDK 1.8.0_312. Error occurred while running `reobfuscate.sh` on Linux Mint, all updates applied. I'm not sure if this has an easy fix or not, but any help would be greatly appreciated.

I can see that it has something to do with zip extraction and a missing class file. But I checked, and I'm fairly certain it's where it should be.

Edit: Full mcp.log [here](https://pastebin.com/DgEx1Dus) & mcperr.log [here](https://pastebin.com/sVRviSLf). Traceback below.

```
Traceback (most recent call last):
  File "runtime/reobfuscate.py", line 51, in <module>
    main(options.config)
  File "runtime/reobfuscate.py", line 30, in main
    commands.unpackreobfclasses(0)
  File "/home/moderator_man/Documents/Projects/MCP-b1.7.3/OSMRewrite-Linux/runtime/commands.py", line 934, in unpackreobfclasses
    zipjar.extract('%s.class' % i, outpathlk[side])
  File "/home/moderator_man/Documents/Projects/MCP-b1.7.3/OSMRewrite-Linux/runtime/bin/python/lib-python/3/zipfile.py", line 1507, in extract
    return self._extract_member(member, path, pwd)
  File "/home/moderator_man/Documents/Projects/MCP-b1.7.3/OSMRewrite-Linux/runtime/bin/python/lib-python/3/zipfile.py", line 1546, in _extract_member
    member = self.getinfo(member)
  File "/home/moderator_man/Documents/Projects/MCP-b1.7.3/OSMRewrite-Linux/runtime/bin/python/lib-python/3/zipfile.py", line 1304, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'com/oldschoolminecraft/client/OSM.class' in the archive"
```

**Comment by Nyvyme** [comment]
Try to run updatemd5.sh before reobfuscate.sh
